//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppConfig
    {
        public long AppConfigId { get; set; }
        public string AppConfigKey { get; set; }
        public string AppConfigValue { get; set; }
    }
}
