//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beacon
    {
        public Beacon()
        {
            this.Stalls = new HashSet<Stall>();
        }
    
        public long BeaconId { get; set; }
        public string Title { get; set; }
        public string UUID { get; set; }
        public string Major { get; set; }
        public string Minor { get; set; }
        public string Proximity { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<Stall> Stalls { get; set; }
    }
}
