//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAppServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventAppDataModelEntity : DbContext
    {
        public EventAppDataModelEntity()
            : base("name=EventAppDataModelEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppConfig> AppConfigs { get; set; }
        public virtual DbSet<Beacon> Beacons { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<PlayerScore> PlayerScores { get; set; }
        public virtual DbSet<RateStall> RateStalls { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Speaker> Speakers { get; set; }
        public virtual DbSet<Stall> Stalls { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TagDetail> TagDetails { get; set; }
        public virtual DbSet<THClueCategory> THClueCategories { get; set; }
        public virtual DbSet<THClue> THClues { get; set; }
        public virtual DbSet<THTeam> THTeams { get; set; }
        public virtual DbSet<THTeamClue> THTeamClues { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserReview> UserReviews { get; set; }
        public virtual DbSet<UserSession> UserSessions { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<UserAttendance> UserAttendances { get; set; }
    }
}
