//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.THTeams = new HashSet<THTeam>();
            this.Users = new HashSet<User>();
            this.PlayerScores = new HashSet<PlayerScore>();
        }
    
        public long LocationId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<THTeam> THTeams { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<PlayerScore> PlayerScores { get; set; }
    }
}
