//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerScore
    {
        public long PlayerScoreId { get; set; }
        public string EmpId { get; set; }
        public Nullable<int> Quiz1Score { get; set; }
        public Nullable<int> Quiz2Score { get; set; }
        public Nullable<int> Quiz3Score { get; set; }
        public Nullable<int> Quiz4Score { get; set; }
        public Nullable<int> LeadershipPosition { get; set; }
        public Nullable<int> CummulativeScore { get; set; }
        public long locationID { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
