//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speaker
    {
        public Speaker()
        {
            this.Sessions = new HashSet<Session>();
        }
    
        public long SpeakerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Description { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Image { get; set; }
        public string Intro { get; set; }
    
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
