//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stall
    {
        public Stall()
        {
            this.RateStalls = new HashSet<RateStall>();
            this.UserAttendances = new HashSet<UserAttendance>();
        }
    
        public long StallId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> BeaconId { get; set; }
    
        public virtual Beacon Beacon { get; set; }
        public virtual ICollection<RateStall> RateStalls { get; set; }
        public virtual ICollection<UserAttendance> UserAttendances { get; set; }
    }
}
