//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagDetail
    {
        public long TagDetailsId { get; set; }
        public long TagId { get; set; }
        public long SessionId { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
