//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THClue
    {
        public THClue()
        {
            this.THTeamClues = new HashSet<THTeamClue>();
        }
    
        public long THClueId { get; set; }
        public string THCluesDescription { get; set; }
        public long THClueCategoryId { get; set; }
        public string THAnswer { get; set; }
        public string THRiddle { get; set; }
    
        public virtual THClueCategory THClueCategory { get; set; }
        public virtual ICollection<THTeamClue> THTeamClues { get; set; }
    }
}
