//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THClueCategory
    {
        public THClueCategory()
        {
            this.THClues = new HashSet<THClue>();
        }
    
        public long THClueCategoryId { get; set; }
        public string THClueCategoryDescription { get; set; }
    
        public virtual ICollection<THClue> THClues { get; set; }
    }
}
