//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THTeamClue
    {
        public long THTeamCluesId { get; set; }
        public long THTeamID { get; set; }
        public long THClueID { get; set; }
        public Nullable<bool> IsValid { get; set; }
    
        public virtual THClue THClue { get; set; }
        public virtual THTeam THTeam { get; set; }
    }
}
