//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReview
    {
        public long UserReviewId { get; set; }
        public long UserId { get; set; }
        public long SessionId { get; set; }
        public int Rating { get; set; }
        public string Comments { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual User User { get; set; }
    }
}
