//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAttendance
    {
        public long UserID { get; set; }
        public long SessionID { get; set; }
        public long StallID { get; set; }
        public bool IsAttendee { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual Stall Stall { get; set; }
        public virtual User User { get; set; }
    }
}
