//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.RateStalls = new HashSet<RateStall>();
            this.UserSessions = new HashSet<UserSession>();
            this.UserReviews = new HashSet<UserReview>();
            this.UserAttendances = new HashSet<UserAttendance>();
        }
    
        public long UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string EmpID { get; set; }
        public string EmailId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public Nullable<long> THTeamId { get; set; }
        public Nullable<bool> ClaimGoody { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<RateStall> RateStalls { get; set; }
        public virtual THTeam THTeam { get; set; }
        public virtual ICollection<UserSession> UserSessions { get; set; }
        public virtual ICollection<UserReview> UserReviews { get; set; }
        public virtual ICollection<UserAttendance> UserAttendances { get; set; }
    }
}
